# Introductory Example
In this example. let's first get familiar withe the concept of scalable data frames in Turi.

These frames are extremely powerful dta astructures that will allow you load data from file and even process data that is too lareg to fit into memory. Everything is subsumed to the programmer, so you need not worry about processing the data any different than a pandas dataframe. Its that simple!

To install Turi, follow this guide:
https://github.com/apple/turicreate

**TL/DR:**   
`pip install -U turicreate`



In [12]:
import turicreate as tc

tc.__version__
titanic_sframe = tc.SFrame("titanic_data.csv")

Finished parsing file /Users/ericlarson/Dropbox/_Teaching/MSLC/Projects/Demonstrations/python_short_examples/titanic_data.csv

Parsing completed. Parsed 100 lines in 0.007713 secs.

------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[int,str,str,str,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------


Finished parsing file /Users/ericlarson/Dropbox/_Teaching/MSLC/Projects/Demonstrations/python_short_examples/titanic_data.csv

Parsing completed. Parsed 2201 lines in 0.005382 secs.

In [13]:
titanic_sframe

Columns:
	X1	int
	Class	str
	Sex	str
	Age	str
	Survived	str

Rows: 2201

Data:
+----+-------+------+-------+----------+
| X1 | Class | Sex  |  Age  | Survived |
+----+-------+------+-------+----------+
| 1  |  3rd  | Male | Child |    No    |
| 2  |  3rd  | Male | Child |    No    |
| 3  |  3rd  | Male | Child |    No    |
| 4  |  3rd  | Male | Child |    No    |
| 5  |  3rd  | Male | Child |    No    |
| 6  |  3rd  | Male | Child |    No    |
| 7  |  3rd  | Male | Child |    No    |
| 8  |  3rd  | Male | Child |    No    |
| 9  |  3rd  | Male | Child |    No    |
| 10 |  3rd  | Male | Child |    No    |
+----+-------+------+-------+----------+
[2201 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

## Visuals
You can explore the use of many custom visuals in Turi here:
- https://apple.github.io/turicreate/docs/userguide/

However, you probably won't need to do too much visualization unless you really want to cusomtize the models that Turi creates. For now, we don't really need that, so lets only show one example. 

In [14]:
# now lets visualize the model
titanic_sframe.show()

Materializing SFrame

## Creating a Model
Now let's use the titanic data to unerstand if we can predict when a person survives based on their class (as a passenger), gender, and age. It is reasonable to assume all these features are good indicators of sirvival.

To do this, we simply need to tell Turi to target the class Survived and use a list of features, like below. The model will automatically try to select the best parameters possible and the best type of classification. No need for our input on this one.

In [15]:
model = tc.classifier.create(titanic_sframe, target='Survived',
                             features = ['Class',
                                         'Sex',
                                         'Age'])

model




PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

PROGRESS: The following methods are available for this type of problem.
PROGRESS: BoostedTreesClassifier, RandomForestClassifier, DecisionTreeClassifier, SVMClassifier, LogisticClassifier
PROGRESS: The returned model will be chosen according to validation accuracy.


Boosted trees classifier:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| Iteration | Elapsed Time | Training Accuracy | Validation Accuracy | Training Log Loss | Validation Log Loss |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| 1         | 0.016978     | 0.788517          | 0.828829            | 0.597679          | 0.588873            |

| 2         | 0.019976     | 0.788517          | 0.828829            | 0.547234          | 0.532713            |

| 3         | 0.023378     | 0.788517          | 0.828829            | 0.518760          | 0.500672            |

| 4         | 0.026703     | 0.788517          | 0.828829            | 0.502228          | 0.482496            |

| 5         | 0.030521     | 0.788517          | 0.828829            | 0.492467          | 0.472277            |

| 10        | 0.045918     | 0.788517          | 0.828829            | 0.478869          | 0.465471            |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

Random forest classifier:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| Iteration | Elapsed Time | Training Accuracy | Validation Accuracy | Training Log Loss | Validation Log Loss |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| 1         | 0.014480     | 0.780861          | 0.828829            | 0.502654          | 0.458412            |

| 2         | 0.017476     | 0.788517          | 0.828829            | 0.495126          | 0.459492            |

| 3         | 0.020468     | 0.788517          | 0.828829            | 0.493530          | 0.459770            |

| 4         | 0.023052     | 0.788517          | 0.828829            | 0.492767          | 0.460752            |

| 5         | 0.025469     | 0.788517          | 0.828829            | 0.500266          | 0.467589            |

| 10        | 0.037704     | 0.788517          | 0.828829            | 0.495161          | 0.463846            |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

Decision tree classifier:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| Iteration | Elapsed Time | Training Accuracy | Validation Accuracy | Training Log Loss | Validation Log Loss |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| 1         | 0.011962     | 0.788517          | 0.828829            | 0.490200          | 0.462552            |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

SVM:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

Number of coefficients    : 6

Starting L-BFGS

--------------------------------------------------------

+-----------+----------+-----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Step size | Elapsed Time | Training Accuracy | Validation Accuracy |

+-----------+----------+-----------+--------------+-------------------+---------------------+

| 0         | 4        | 3.000000  | 0.000916     | 0.734928          | 0.792793            |

| 1         | 7        | 1.500000  | 0.002217     | 0.741148          | 0.774775            |

| 2         | 9        | 1.371268  | 0.003142     | 0.748804          | 0.783784            |

| 3         | 10       | 1.371268  | 0.004058     | 0.559330          | 0.549550            |

| 4         | 14       | 0.093958  | 0.005422     | 0.776555          | 0.810811            |

| 9         | 22       | 0.502012  | 0.009652     | 0.774163          | 0.810811            |

+-----------+----------+-----------+--------------+-------------------+---------------------+

Logistic regression:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

Number of coefficients      : 6

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Elapsed Time | Training Accuracy | Validation Accuracy |

+-----------+----------+--------------+-------------------+---------------------+

| 1         | 2        | 0.001345     | 0.776555          | 0.810811            |

| 2         | 3        | 0.002362     | 0.776555          | 0.810811            |

| 3         | 4        | 0.003844     | 0.776555          | 0.810811            |

| 4         | 5        | 0.005164     | 0.776555          | 0.810811            |

+-----------+----------+--------------+-------------------+---------------------+

SUCCESS: Optimal solution found.

PROGRESS: Model selection based on validation accuracy:
PROGRESS: ---------------------------------------------
PROGRESS: BoostedTreesClassifier          : 0.8288288288288288
PROGRESS: RandomForestClassifier          : 0.8288288288288288
PROGRESS: DecisionTreeClassifier          : 0.8288288288288288
PROGRESS: SVMClassifier                   : 0.8108108108108109
PROGRESS: LogisticClassifier              : 0.8108108108108109
PROGRESS: ---------------------------------------------
PROGRESS: Selecting BoostedTreesClassifier based on validation set performance.


Class                          : BoostedTreesClassifier

Schema
------
Number of examples             : 2090
Number of feature columns      : 3
Number of unpacked features    : 3
Number of classes              : 2

Settings
--------
Number of trees                : 10
Max tree depth                 : 6
Training time (sec)            : 0.0466
Training accuracy              : 0.7885
Validation accuracy            : 0.8288
Training log_loss              : 0.4789
Validation log_loss            : 0.4655
Training auc                   : 0.7679
Validation auc                 : 0.7786

In [16]:
# Save and use the best model
model.save('titanic_classifier')

In [17]:
# load model from file
model_loaded = tc.load_model('titanic_classifier')

model_loaded.evaluate(titanic_sframe)

{'accuracy': 0.7905497501135847,
 'auc': 0.7683128970445258,
 'confusion_matrix': Columns:
 	target_label	str
 	predicted_label	str
 	count	int
 
 Rows: 4
 
 Data:
 +--------------+-----------------+-------+
 | target_label | predicted_label | count |
 +--------------+-----------------+-------+
 |     Yes      |        No       |  441  |
 |      No      |        No       |  1470 |
 |      No      |       Yes       |   20  |
 |     Yes      |       Yes       |  270  |
 +--------------+-----------------+-------+
 [4 rows x 3 columns],
 'f1_score': 0.5394605394605394,
 'log_loss': 0.4781933330214533,
 'precision': 0.9310344827586207,
 'recall': 0.379746835443038,
 'roc_curve': Columns:
 	threshold	float
 	fpr	float
 	tpr	float
 	p	int
 	n	int
 
 Rows: 1001
 
 Data:
 +-----------+-----+-----+-----+------+
 | threshold | fpr | tpr |  p  |  n   |
 +-----------+-----+-----+-----+------+
 |    0.0    | 1.0 | 1.0 | 711 | 1490 |
 |   0.001   | 1.0 | 1.0 | 711 | 1490 |
 |   0.002   | 1.0 | 1.0 | 

In [18]:
yhat = model_loaded.predict(titanic_sframe)
y = titanic_sframe['Survived']

# print out accuracy
sum(yhat==y)/len(y)

0.7905497501135847

# An example with Iris Data
Now let's do a very simple example with all code embedded nicely. To create an SFrame from Numpy data, we need to have some intermediate representation. Here, I will use pandas, but we could easily use something like a dictionary.

In [19]:
import turicreate as tc
from sklearn import datasets as ds
import numpy as np
import pandas as pd

bunch = ds.load_iris()

# make pandas DataFrame from numpy array for insertion
df_tmp = pd.DataFrame(bunch.data,columns=bunch.feature_names)
df_tmp['target'] = bunch.target_names[bunch.target]

iris_sframe = tc.SFrame(data=df_tmp)

print(iris_sframe)

# clean up memory
del df_tmp, bunch

model = tc.classifier.create(iris_sframe, target='target', verbose=0)
print(model)
yhat_sframe = model.classify(iris_sframe)
yhat_sframe

+-------------------+------------------+-------------------+------------------+
| sepal length (cm) | sepal width (cm) | petal length (cm) | petal width (cm) |
+-------------------+------------------+-------------------+------------------+
|        5.1        |       3.5        |        1.4        |       0.2        |
|        4.9        |       3.0        |        1.4        |       0.2        |
|        4.7        |       3.2        |        1.3        |       0.2        |
|        4.6        |       3.1        |        1.5        |       0.2        |
|        5.0        |       3.6        |        1.4        |       0.2        |
|        5.4        |       3.9        |        1.7        |       0.4        |
|        4.6        |       3.4        |        1.4        |       0.3        |
|        5.0        |       3.4        |        1.5        |       0.2        |
|        4.4        |       2.9        |        1.4        |       0.2        |
|        4.9        |       3.1        |

Columns:
	class	str
	probability	float

Rows: 150

Data:
+--------+--------------------+
| class  |    probability     |
+--------+--------------------+
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
| setosa | 0.9523611068725586 |
+--------+--------------------+
[150 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

# Same Example with a Dictionary

In [20]:
# now let's repeat using a dictionary
import turicreate as tc
from sklearn import datasets as ds
import numpy as np

bunch = ds.load_iris()

# make dictionary from numpy array for insertion
tmp_dict = {'target':bunch.target_names[bunch.target]}
tmp_dict['features'] = bunch.data

iris_sframe = tc.SFrame(data=tmp_dict)
print(iris_sframe)

# clean up memory
del tmp_dict, bunch

model = tc.classifier.create(iris_sframe, target='target', verbose=0)
print(model)
yhat_sframe = model.classify(iris_sframe)
yhat_sframe

+-------------------+--------+
|      features     | target |
+-------------------+--------+
| [5.1 3.5 1.4 0.2] | setosa |
| [4.9 3.  1.4 0.2] | setosa |
| [4.7 3.2 1.3 0.2] | setosa |
| [4.6 3.1 1.5 0.2] | setosa |
| [5.  3.6 1.4 0.2] | setosa |
| [5.4 3.9 1.7 0.4] | setosa |
| [4.6 3.4 1.4 0.3] | setosa |
| [5.  3.4 1.5 0.2] | setosa |
| [4.4 2.9 1.4 0.2] | setosa |
| [4.9 3.1 1.5 0.1] | setosa |
+-------------------+--------+
[150 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
Class                          : BoostedTreesClassifier

Schema
------
Number of examples             : 142
Number of feature columns      : 1
Number of unpacked features    : 4
Number of classes              : 3

Settings
--------
Number of trees                : 30
Max tree depth                 : 6
Training time (sec)            : 0.0535
Training accuracy              : 1.0
Validation accuracy            : 1.

Columns:
	class	str
	probability	float

Rows: 150

Data:
+--------+--------------------+
| class  |    probability     |
+--------+--------------------+
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
| setosa | 0.9525057077407837 |
+--------+--------------------+
[150 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

# Yet another Example
Now let's use the digits example from sklearn! Or some example thst you want!

In [22]:
from sklearn.datasets import load_digits

bunch = load_digits()

digit_sframe = tc.SFrame({'features':bunch.data,'number':bunch.target})
print(digit_sframe)

# clean up memory
del bunch

model = tc.classifier.create(digit_sframe, target='number', verbose=0)
print(model)
yhat_sframe = model.classify(digit_sframe)
yhat_sframe

+-------------------------------+--------+
|            features           | number |
+-------------------------------+--------+
| [1.423e+01 1.710e+00 2.430... |   0    |
| [1.32e+01 1.78e+00 2.14e+0... |   0    |
| [1.316e+01 2.360e+00 2.670... |   0    |
| [1.437e+01 1.950e+00 2.500... |   0    |
| [1.324e+01 2.590e+00 2.870... |   0    |
| [1.42e+01 1.76e+00 2.45e+0... |   0    |
| [1.439e+01 1.870e+00 2.450... |   0    |
| [1.406e+01 2.150e+00 2.610... |   0    |
| [1.483e+01 1.640e+00 2.170... |   0    |
| [1.386e+01 1.350e+00 2.270... |   0    |
+-------------------------------+--------+
[178 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
Class                          : BoostedTreesClassifier

Schema
------
Number of examples             : 169
Number of feature columns      : 1
Number of unpacked features    : 13
Number of classes              : 3

Settings
--------
Number of tree

Columns:
	class	int
	probability	float

Rows: 178

Data:
+-------+--------------------+
| class |    probability     |
+-------+--------------------+
|   0   | 0.9561968445777893 |
|   0   | 0.9561968445777893 |
|   0   | 0.9561968445777893 |
|   0   | 0.9561968445777893 |
|   0   | 0.8977226614952087 |
|   0   | 0.9561968445777893 |
|   0   | 0.9561968445777893 |
|   0   | 0.9561968445777893 |
|   0   | 0.9561968445777893 |
|   0   | 0.9561968445777893 |
+-------+--------------------+
[178 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.