# Introductory Example
In this example. let's first get familiar withe the concept of scalable data frames in Turi.

These frames are extremely powerful dta astructures that will allow you load data from file and even process data that is too lareg to fit into memory. Everything is subsumed to the programmer, so you need not worry about processing the data any different than a pandas dataframe. Its that simple!

To install Turi, follow this guide:
https://github.com/apple/turicreate

**TL/DR:**   
`pip install -U turicreate`



In [3]:
!head titanic_data.csv

,Class,Sex,Age,Survived
1,3rd,Male,Child,No
2,3rd,Male,Child,No
3,3rd,Male,Child,No
4,3rd,Male,Child,No
5,3rd,Male,Child,No
6,3rd,Male,Child,No
7,3rd,Male,Child,No
8,3rd,Male,Child,No
9,3rd,Male,Child,No


In [5]:
import turicreate as tc

print(tc.__version__)
titanic_sframe = tc.SFrame("titanic_data.csv")

6.4.1


Finished parsing file /Users/eclarson/Dropbox/_Teaching/MSLC/Projects/Demonstrations/python_short_examples/titanic_data.csv

------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[int,str,str,str,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------


Parsing completed. Parsed 100 lines in 0.009863 secs.

Finished parsing file /Users/eclarson/Dropbox/_Teaching/MSLC/Projects/Demonstrations/python_short_examples/titanic_data.csv

Parsing completed. Parsed 2201 lines in 0.003095 secs.

In [6]:
titanic_sframe

Columns:
	X1	int
	Class	str
	Sex	str
	Age	str
	Survived	str

Rows: 2201

Data:
+----+-------+------+-------+----------+
| X1 | Class | Sex  |  Age  | Survived |
+----+-------+------+-------+----------+
| 1  |  3rd  | Male | Child |    No    |
| 2  |  3rd  | Male | Child |    No    |
| 3  |  3rd  | Male | Child |    No    |
| 4  |  3rd  | Male | Child |    No    |
| 5  |  3rd  | Male | Child |    No    |
| 6  |  3rd  | Male | Child |    No    |
| 7  |  3rd  | Male | Child |    No    |
| 8  |  3rd  | Male | Child |    No    |
| 9  |  3rd  | Male | Child |    No    |
| 10 |  3rd  | Male | Child |    No    |
+----+-------+------+-------+----------+
[2201 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

## Visuals
You can explore the use of many custom visuals in Turi here:
- https://apple.github.io/turicreate/docs/userguide/

However, you probably won't need to do too much visualization unless you really want to cusomtize the models that Turi creates. For now, we don't really need that, so lets only show one example. 

In [7]:
# now lets visualize the model
titanic_sframe.show()

Materializing SFrame

## Creating a Model
Now let's use the titanic data to unerstand if we can predict when a person survives based on their class (as a passenger), gender, and age. It is reasonable to assume all these features are good indicators of sirvival.

To do this, we simply need to tell Turi to target the class Survived and use a list of features, like below. The model will automatically try to select the best parameters possible and the best type of classification. No need for our input on this one.

In [8]:
model = tc.classifier.create(titanic_sframe, target='Survived',
                             features = ['Class',
                                         'Sex',
                                         'Age'])

model




PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

PROGRESS: The following methods are available for this type of problem.
PROGRESS: BoostedTreesClassifier, RandomForestClassifier, DecisionTreeClassifier, SVMClassifier, LogisticClassifier
PROGRESS: The returned model will be chosen according to validation accuracy.


Boosted trees classifier:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| Iteration | Elapsed Time | Training Accuracy | Validation Accuracy | Training Log Loss | Validation Log Loss |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| 1         | 0.007832     | 0.788995          | 0.819820            | 0.597439          | 0.590971            |

| 2         | 0.028581     | 0.788995          | 0.819820            | 0.546948          | 0.535751            |

| 3         | 0.037843     | 0.788995          | 0.819820            | 0.518498          | 0.504211            |

| 4         | 0.046608     | 0.788995          | 0.819820            | 0.502051          | 0.485731            |

| 5         | 0.055220     | 0.788995          | 0.819820            | 0.492405          | 0.474760            |

| 10        | 0.074089     | 0.788995          | 0.819820            | 0.479344          | 0.459816            |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

Random forest classifier:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| Iteration | Elapsed Time | Training Accuracy | Validation Accuracy | Training Log Loss | Validation Log Loss |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| 1         | 0.001934     | 0.788995          | 0.819820            | 0.490218          | 0.470970            |

| 2         | 0.003901     | 0.788995          | 0.819820            | 0.490580          | 0.472115            |

| 3         | 0.005301     | 0.788995          | 0.819820            | 0.492962          | 0.469383            |

| 4         | 0.007407     | 0.788995          | 0.819820            | 0.492350          | 0.468957            |

| 5         | 0.009049     | 0.788995          | 0.819820            | 0.492194          | 0.469144            |

| 10        | 0.018388     | 0.788995          | 0.819820            | 0.492407          | 0.470075            |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

Decision tree classifier:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| Iteration | Elapsed Time | Training Accuracy | Validation Accuracy | Training Log Loss | Validation Log Loss |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

| 1         | 0.002570     | 0.788995          | 0.819820            | 0.490313          | 0.471605            |

+-----------+--------------+-------------------+---------------------+-------------------+---------------------+

SVM:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

Number of coefficients    : 6

Starting L-BFGS

--------------------------------------------------------

+-----------+----------+-----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Step size | Elapsed Time | Training Accuracy | Validation Accuracy |

+-----------+----------+-----------+--------------+-------------------+---------------------+

| 0         | 4        | 3.000000  | 0.001850     | 0.673684          | 0.720721            |

| 1         | 7        | 1.500000  | 0.003637     | 0.740191          | 0.792793            |

| 2         | 10       | 1.335516  | 0.005140     | 0.748325          | 0.792793            |

| 3         | 11       | 1.335516  | 0.006078     | 0.561244          | 0.513514            |

| 4         | 16       | 0.338045  | 0.008271     | 0.777512          | 0.792793            |

| 9         | 24       | 0.255529  | 0.013185     | 0.775120          | 0.792793            |

+-----------+----------+-----------+--------------+-------------------+---------------------+

Logistic regression:

--------------------------------------------------------

Number of examples          : 2090

Number of classes           : 2

Number of feature columns   : 3

Number of unpacked features : 3

Number of coefficients      : 6

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Elapsed Time | Training Accuracy | Validation Accuracy |

+-----------+----------+--------------+-------------------+---------------------+

| 1         | 2        | 0.001353     | 0.777512          | 0.792793            |

| 2         | 3        | 0.002414     | 0.777512          | 0.792793            |

| 3         | 4        | 0.003381     | 0.777512          | 0.792793            |

| 4         | 5        | 0.004401     | 0.777512          | 0.792793            |

+-----------+----------+--------------+-------------------+---------------------+

SUCCESS: Optimal solution found.

PROGRESS: Model selection based on validation accuracy:
PROGRESS: ---------------------------------------------
PROGRESS: BoostedTreesClassifier          : 0.8198198198198198
PROGRESS: RandomForestClassifier          : 0.8198198198198198
PROGRESS: DecisionTreeClassifier          : 0.8198198198198198
PROGRESS: SVMClassifier                   : 0.7927927927927928
PROGRESS: LogisticClassifier              : 0.7927927927927928
PROGRESS: ---------------------------------------------
PROGRESS: Selecting BoostedTreesClassifier based on validation set performance.


Class                          : BoostedTreesClassifier

Schema
------
Number of examples             : 2090
Number of feature columns      : 3
Number of unpacked features    : 3
Number of classes              : 2

Settings
--------
Number of trees                : 10
Max tree depth                 : 6
Training time (sec)            : 0.0744
Training accuracy              : 0.789
Validation accuracy            : 0.8198
Training log_loss              : 0.4793
Validation log_loss            : 0.4598
Training auc                   : 0.7694
Validation auc                 : 0.7416

In [9]:
# Save and use the best model
model.save('titanic_classifier')

In [10]:
# load model from file
model_loaded = tc.load_model('titanic_classifier')

model_loaded.evaluate(titanic_sframe)

{'accuracy': 0.7905497501135847,
 'auc': 0.7682694758304308,
 'confusion_matrix': Columns:
 	target_label	str
 	predicted_label	str
 	count	int
 
 Rows: 4
 
 Data:
 +--------------+-----------------+-------+
 | target_label | predicted_label | count |
 +--------------+-----------------+-------+
 |     Yes      |        No       |  441  |
 |      No      |        No       |  1470 |
 |      No      |       Yes       |   20  |
 |     Yes      |       Yes       |  270  |
 +--------------+-----------------+-------+
 [4 rows x 3 columns],
 'f1_score': 0.5394605394605394,
 'log_loss': 0.4783595893429514,
 'precision': 0.9310344827586207,
 'recall': 0.379746835443038,
 'roc_curve': Columns:
 	threshold	float
 	fpr	float
 	tpr	float
 	p	int
 	n	int
 
 Rows: 1001
 
 Data:
 +-----------+-----+-----+-----+------+
 | threshold | fpr | tpr |  p  |  n   |
 +-----------+-----+-----+-----+------+
 |    0.0    | 1.0 | 1.0 | 711 | 1490 |
 |   0.001   | 1.0 | 1.0 | 711 | 1490 |
 |   0.002   | 1.0 | 1.0 | 

In [11]:
yhat = model_loaded.predict(titanic_sframe)
y = titanic_sframe['Survived']

# print out accuracy
sum(yhat==y)/len(y)

0.7905497501135847

# Repeat with Scikit-learn
Now let's try this again using scikit learn

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

X = titanic_sframe['Class','Sex','Age'].to_dataframe()
y = titanic_sframe['Survived'].to_numpy()

# properly process the data for input
X = OneHotEncoder().fit_transform(X)

# separate data 
X_train, X_test, y_train, y_test = train_test_split(X,y)

# training and fitting of the model
clf = RandomForestClassifier()

clf.fit(X_train,y_train)
yhat = clf.predict(X_test)

# print out accuracy
sum(yhat==y_test)/len(y_test)

0.7931034482758621

# An example with Iris Data
Now let's do a very simple example with all code embedded nicely. To create an SFrame from Numpy data, we need to have some intermediate representation. Here, I will use pandas, but we could easily use something like a dictionary.

In [13]:
import turicreate as tc
from sklearn import datasets as ds
import numpy as np
import pandas as pd

bunch = ds.load_iris()

# make pandas DataFrame from numpy array for insertion
df_tmp = pd.DataFrame(bunch.data,columns=bunch.feature_names)
df_tmp['target'] = bunch.target_names[bunch.target]

# convert into SFrame
iris_sframe = tc.SFrame(data=df_tmp)
print(iris_sframe)

# clean up memory
del df_tmp, bunch

# now create iris classifier
model = tc.classifier.create(iris_sframe, target='target', verbose=0)
print(model)
yhat_sframe = model.classify(iris_sframe)
yhat_sframe

+-------------------+------------------+-------------------+------------------+
| sepal length (cm) | sepal width (cm) | petal length (cm) | petal width (cm) |
+-------------------+------------------+-------------------+------------------+
|        5.1        |       3.5        |        1.4        |       0.2        |
|        4.9        |       3.0        |        1.4        |       0.2        |
|        4.7        |       3.2        |        1.3        |       0.2        |
|        4.6        |       3.1        |        1.5        |       0.2        |
|        5.0        |       3.6        |        1.4        |       0.2        |
|        5.4        |       3.9        |        1.7        |       0.4        |
|        4.6        |       3.4        |        1.4        |       0.3        |
|        5.0        |       3.4        |        1.5        |       0.2        |
|        4.4        |       2.9        |        1.4        |       0.2        |
|        4.9        |       3.1        |

Columns:
	class	str
	probability	float

Rows: 150

Data:
+--------+--------------------+
| class  |    probability     |
+--------+--------------------+
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
| setosa | 0.9520875215530396 |
+--------+--------------------+
[150 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

# Same Example with a Dictionary

In [14]:
# now let's repeat using a dictionary
import turicreate as tc
from sklearn import datasets as ds
import numpy as np

bunch = ds.load_iris()

# make dictionary from numpy array for insertion
tmp_dict = {'target':bunch.target_names[bunch.target]}
tmp_dict['features'] = bunch.data

# now use dict() to create SFrame
iris_sframe = tc.SFrame(data=tmp_dict)
print(iris_sframe)

# clean up memory
del tmp_dict, bunch

model = tc.classifier.create(iris_sframe, target='target', verbose=0)
print(model)
yhat_sframe = model.classify(iris_sframe)
yhat_sframe

+-------------------+--------+
|      features     | target |
+-------------------+--------+
| [5.1 3.5 1.4 0.2] | setosa |
| [4.9 3.  1.4 0.2] | setosa |
| [4.7 3.2 1.3 0.2] | setosa |
| [4.6 3.1 1.5 0.2] | setosa |
| [5.  3.6 1.4 0.2] | setosa |
| [5.4 3.9 1.7 0.4] | setosa |
| [4.6 3.4 1.4 0.3] | setosa |
| [5.  3.4 1.5 0.2] | setosa |
| [4.4 2.9 1.4 0.2] | setosa |
| [4.9 3.1 1.5 0.1] | setosa |
+-------------------+--------+
[150 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
Class                          : BoostedTreesClassifier

Schema
------
Number of examples             : 142
Number of feature columns      : 1
Number of unpacked features    : 4
Number of classes              : 3

Settings
--------
Number of trees                : 30
Max tree depth                 : 6
Training time (sec)            : 0.0342
Training accuracy              : 1.0
Validation accuracy            : 1.

Columns:
	class	str
	probability	float

Rows: 150

Data:
+--------+-------------------+
| class  |    probability    |
+--------+-------------------+
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
| setosa | 0.951894223690033 |
+--------+-------------------+
[150 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

# Yet another Example
Now let's use the digits example from sklearn! Or some example that you want!

In [15]:
from sklearn.datasets import load_digits

bunch = load_digits()

digit_sframe = tc.SFrame({'features':bunch.data,'number':bunch.target})
print(digit_sframe)

# clean up memory
del bunch

model = tc.classifier.create(digit_sframe, target='number', verbose=0)
print(model)
yhat_sframe = model.classify(digit_sframe)
yhat_sframe

+-------------------------------+--------+
|            features           | number |
+-------------------------------+--------+
| [ 0.  0.  5. 13.  9.  1.  ... |   0    |
| [ 0.  0.  0. 12. 13.  5.  ... |   1    |
| [ 0.  0.  0.  4. 15. 12.  ... |   2    |
| [ 0.  0.  7. 15. 13.  1.  ... |   3    |
| [ 0.  0.  0.  1. 11.  0.  ... |   4    |
| [ 0.  0. 12. 10.  0.  0.  ... |   5    |
| [ 0.  0.  0. 12. 13.  0.  ... |   6    |
| [ 0.  0.  7.  8. 13. 16. 1... |   7    |
| [ 0.  0.  9. 14.  8.  1.  ... |   8    |
| [ 0.  0. 11. 12.  0.  0.  ... |   9    |
+-------------------------------+--------+
[1797 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
Class                          : BoostedTreesClassifier

Schema
------
Number of examples             : 1707
Number of feature columns      : 1
Number of unpacked features    : 64
Number of classes              : 10

Settings
--------
Number of t

Columns:
	class	int
	probability	float

Rows: 1797

Data:
+-------+--------------------+
| class |    probability     |
+-------+--------------------+
|   0   | 0.9424105882644653 |
|   1   | 0.9286558032035828 |
|   2   | 0.8880395293235779 |
|   3   | 0.8976808190345764 |
|   4   | 0.9300089478492737 |
|   5   | 0.7819111347198486 |
|   6   | 0.941036581993103  |
|   7   | 0.9308833479881287 |
|   8   | 0.9302364587783813 |
|   9   | 0.8000986576080322 |
+-------+--------------------+
[1797 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [16]:
model.validation_report_by_class

Columns:
	actual_count	int
	class	int
	missed_predicting_this	int
	precision	float
	predicted_correctly	int
	predicted_this_incorrectly	int
	recall	float

Rows: 10

Data:
+--------------+-------+------------------------+--------------------+---------------------+
| actual_count | class | missed_predicting_this |     precision      | predicted_correctly |
+--------------+-------+------------------------+--------------------+---------------------+
|      4       |   0   |           0            |        0.8         |          4          |
|      12      |   1   |           1            | 0.9166666666666666 |          11         |
|      8       |   2   |           0            |        1.0         |          8          |
|      5       |   3   |           0            | 0.8333333333333334 |          5          |
|      10      |   4   |           0            |        1.0         |          10         |
|      9       |   5   |           0            |        1.0         |          9          |
|      11      |   6   |           1            |        1.0         |          10         |
|      9       |   7   |           0            |        1.0         |          9          |
|      11      |   8   |           1            | 0.9090909090909091 |          10         |
|      11      |   9   |           1            |        1.0         |          10         |
+--------------+-------+------------------------+--------------------+---------------------+
+----------------------------+--------------------+
| predicted_this_incorrectly |       recall       |
+----------------------------+--------------------+
|             1              |        1.0         |
|             1              | 0.9166666666666666 |
|             0              |        1.0         |
|             1              |        1.0         |
|             0              |        1.0         |
|             0              |        1.0         |
|             0              | 0.9090909090909091 |
|             0              |        1.0         |
|             1              | 0.9090909090909091 |
|             0              | 0.9090909090909091 |
+----------------------------+--------------------+
[10 rows x 7 columns]

In [17]:
digit_sframe.show()

Materializing SFrame

Warning: Skipping column 'features'. Unable to show columns of type 'ndarray'; only [int, float, str] can be shown.

Further warnings of unsupported type will be suppressed.